FROM php:7.4-fpm

RUN apt-get update && apt-get install -y \
    nginx \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libwebp-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    zip \
    unzip   



# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .
RUN touch .env.example .env
RUN chown -R www-data:www-data /var/www/html
RUN composer install
RUN chmod o+w ./storage/ -R
RUN chmod o+w ./public/ -R

RUN chmod o+w /var/www/html/storage/ -R
RUN chmod o+w /var/www/html/public/ -R